apiVersion: v1
kind: ServiceAccount
metadata:
  name: clinical-analyzer
  namespace: ehr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clinical-analyzer
  namespace: ehr
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: ["argoproj.io"]
    resources: ["rollouts"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clinical-analyzer
  namespace: ehr
subjects:
  - kind: ServiceAccount
    name: clinical-analyzer
    namespace: ehr
roleRef:
  kind: Role
  name: clinical-analyzer
  apiGroup: rbac.authorization.k8s.io
